### PR TITLE
Updating agent to Ubuntu 18.04 and adding Azure DevOps yaml build pipeline

### PR DESCRIPTION
**Pull request by naustin**

### CODE REVIEW

**Review by ganrad — CHANGES_REQUESTED** [review]
@naustin Please remove private info. as this is a public repo.  Update values for dockerRegistryServiceConnection & containerRegistry with sample values such as xyz.azurecr.io.  Re-submit and I will merge the updates.  Thx.

**Review by ganrad — CHANGES_REQUESTED** [review]
@naustin This is a public repo. and we can't use acr names!  Can't merge requested updates.  Thx.

**Review by ganrad — CHANGES_REQUESTED** [review]
Can't include private info. in a public repo.  Repo. users are expected to substitute actual values for place holders!  Thx.

**Review by ganrad — COMMENTED** [review]
Thanks for pointing this out.  I will update the dockerfile to use Ubuntu 18.04 LTS and also make a couple of the other changes you have suggested.  Thanks.

**Comment by naustin** [comment]
closing this PR

**Pull request closed without merging**
